### ISSUE TITLE
Update SDK to be compliant with spec v0.2.0

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/java-sdk#42]
Update the SDK to be compliant with the v0.2.0 spec.

- [x] https://github.com/open-feature/java-sdk/issues/43

## Flag Evaluation API
- [x]  [#116](https://github.com/open-feature/spec/pull/116) - Have different methods for float and int

## Providers
- [x]  [#119](https://github.com/open-feature/spec/pull/119) - Remove context transformers. Add provider hooks

## Evaluation Context
- [x]  [#117](https://github.com/open-feature/spec/pull/117) - Ensure context merging behavior is correct
- [x]  [#120](https://github.com/open-feature/spec/pull/120) - Add the ability to fetch all custom fields
- [x]  [#121](https://github.com/open-feature/spec/pull/121) - Ensure evaluation context keys are unique

## Hooks
- [x]  [#119](https://github.com/open-feature/spec/pull/119) - Ensure provider hook are correctly ordered

**Full Changelog**: https://github.com/open-feature/spec/compare/v0.1.0...v0.2.0

**Comment by justinabrahms** [comment]
Still remaining:
```
In the spec, but not in our tests: 
  4.4.7: If an error occurs in the before hooks, the default value MUST be returned.
  3.2.1: The API, Client and invocation MUST have a method for supplying evaluation context.
  3.2.2: Evaluation context MUST be merged in the order: API (global) - client - invocation, with duplicate values being overwritten.
  3.1.4: The evaluation context fields MUST have an unique key.
```

**Comment by justinabrahms** [comment]
Done. We'll call this ticket done when #43 is resolved.

**Comment by beeme1mr** [comment]
Great, thanks Justin.

**Comment by beeme1mr** [comment]
Ah, sorry. I misread your comment. I'll leave it alone 😃
