### ISSUE TITLE
[FEATURE] Make provider interface "stateless", SDK maintains provider state

### ISSUE THREAD

**Issue by toddbaert** [open-feature/java-sdk#844]
#### Stateless providers

Providers no longer maintain their own state: the state for each provider is maintained in the SDK automatically, and updated according to the success/failures of lifecycle methods (init/shutdown) or events emitted from providers spontaneously.

Similar work in C#: https://github.com/open-feature/dotnet-sdk/pull/276

```[tasklist]
### Tasks
- [x] [Requirement 1.7.1](https://openfeature.dev/specification/sections/flag-evaluation#requirement-171): The client MUST define a provider status accessor which indicates the readiness of the associated provider, with possible values NOT_READY, READY, STALE, ERROR, or FATAL.
- [x] [Requirement 1.7.3](https://openfeature.dev/specification/sections/flag-evaluation#requirement-173): The client's provider status accessor MUST indicate READY if the initialize function of the associated provider terminates normally.
- [x] [Requirement 1.7.4](https://openfeature.dev/specification/sections/flag-evaluation#requirement-174): The client's provider status accessor MUST indicate ERROR if the initialize function of the associated provider terminates abnormally.
- [x] [Requirement 1.7.5](https://openfeature.dev/specification/sections/flag-evaluation#requirement-175): The client's provider status accessor MUST indicate FATAL if the initialize function of the associated provider terminates abnormally and indicates error code PROVIDER_FATAL.
- [x] [Requirement 1.7.6](https://openfeature.dev/specification/sections/flag-evaluation#requirement-176): The client MUST default, run error hooks, and indicate an error if flag resolution is attempted while the provider is in NOT_READY.
- [x] [Requirement 1.7.7](https://openfeature.dev/specification/sections/flag-evaluation#requirement-177): The client MUST default, run error hooks, and indicate an error if flag resolution is attempted while the provider is in FATAL.
- [x] [Requirement 1.7.8](https://openfeature.dev/specification/sections/flag-evaluation#requirement-178): Implementations SHOULD propagate the error code returned from any provider lifecycle methods.
- [x] [Requirement 5.1.5](https://openfeature.dev/specification/sections/events#requirement-515): PROVIDER_ERROR events SHOULD populate the provider event details's error code field.
- [x] [Requirement 5.3.5](https://openfeature.dev/specification/sections/events#requirement-535): If the provider emits an event, the value of the client's provider status MUST be updated accordingly.
```

**Comment by gunishmatta** [comment]
Hi @toddbaert  I would like to work on this.

**Comment by beeme1mr** [comment]
Thanks, @gunishmatta, I've assigned you the issue. Please let us know if you have any questions!

**Comment by toddbaert** [comment]
@gunishmatta here's the implementation I did in the JS SDK: https://github.com/open-feature/js-sdk/pull/795.

You can disregard the `RECONCILING` stuff - that only applies to client-side SDKs, which Java is not. The relevant stuff is all around the `ProviderState`. I used an internal wrapper class for this: https://github.com/open-feature/js-sdk/pull/795/files#diff-918e59c039e8a552dd77bdf93d9759acc86f58f677bf52e7a0990ff92683ef11R25, but take whatever approach you want.

**Comment by gunishmatta** [comment]
@toddbaert  Thanks a lot for the guidance, you can expect my PR by end of this week.

Thanks
Gunish.

**Comment by toddbaert** [comment]
Unassigned due to inactivity.

**Comment by chrfwow** [comment]
Hi @toddbaert I would like to work on this.

**Comment by toddbaert** [comment]
I think this is done with https://github.com/open-feature/java-sdk/pull/1096. I will confirm and close in the next couple days.
